# File: D:\RS Ananda\lis-service\env\docker\mysql\Dockerfile

# Menggunakan image MySQL 8.0 resmi sebagai basis
FROM mysql/mysql-server:8.0

COPY ./create_test_db.sh   /docker-entrypoint-initdb.d/10-create_test_db.sh